# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyDataStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_key', models.CharField(db_index=True, max_length=80)),
                ('db_category', models.CharField(blank=True, max_length=80, null=True)),
                ('db_text', models.TextField(blank=True, null=True)),
                ('db_date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
            ],
        ),
    ]
